---
# Description: Changes a user's password on all linux academy servers
# Assumptions: dig, expect and ssh-keyscan is available on the local system

- hosts: localhost
  gather_facts: "False"

  vars_prompt:
    - name: user
      prompt: >-
        "Enter your Linux Academy Username
        or add [ -e user=your_lnx_acdmy_username ]"
      private: "no"

    - name: suffix
      prompt: >-
        "Use alternate server name
        (eg. username1b.mylabserver.com)? (y/n/yes/no)
        or add [ -e suffix=n ]"
      default: "no"
      private: "no"

    - name: default_key
      prompt: >-
        "Use your default ssh private/public key files? (y/n/yes/no)"
      default: "yes"
      private: "no"

  vars:
    linux_academy_username: "{{ user }}"

  tasks:
    - name: Ensure Linux Academy username is provided
      fail:
        msg: Enter your Linux Academy Username! Add '-e user=lnx_acdmy_username'
      when: user == ""

    - name: Set facts about host
      set_fact:
        server_suffix:
          "{{ 'b' if (suffix|regex_search('(?i)^(y|true)')) else '' }}"
        key_file:
          "{{ (lookup('env','HOME') + '/.ssh/id_rsa')
              if (default_key|regex_search('(?i)^(y|true)'))
              else '{{ playbook_dir }}/id_rsa_la_servers' }}"

    - name: >-
        "Add Hosts {{ linux_academy_username }}[1-6]{{ server_suffix
        }}.mylabserver.com based on username"
      add_host:
        name:
          "{{ linux_academy_username + item + server_suffix }}.mylabserver.com"
        groups: all
        server_prefix: "{{ linux_academy_username + item }}"
        key_file: "{{ key_file }}"
      with_sequence: start=1 end=6

- hosts: "all"
  gather_facts: "no"
  vars:
    ansible_ssh_extra_args: "-o PubkeyAuthentication=no -i {{ key_file }}"

  vars_prompt:
    - name: ssh_user
      default: user
      prompt: "Enter your SSH username"

    - name: ssh_pass
      default: 123456
      prompt: "Enter your current SSH password"

    - name: new_ssh_pass
      prompt: "Enter your new super secure password"

    - name: new_ssh_pass2
      prompt: "Re-Enter your new super secure password"

  roles:
    - change_linux_academy_server_password
...
